export interface IndustryScenario {
  id: string
  name: string
  icon: string
  color: string
  description: string
  compliance: string[]
  specialRequirements: string[]
  commonDevices: string[]
  networkSegments: string[]
  securityPolicies: string[]
  riskFactors: string[]
  sampleSites: Array<{
    name: string
    type: string
    users: number
    devices: number
    location: string
    priority: string
    budget: number
    timeline: string
    specialRequirements: string[]
  }>
}

export const INDUSTRY_SCENARIOS: Record<string, IndustryScenario> = {
  healthcare: {
    id: "healthcare",
    name: "Healthcare",
    icon: "🏥",
    color: "#EF4444",
    description: "Healthcare organizations with strict HIPAA compliance requirements and medical device security",
    compliance: ["HIPAA", "HITECH", "FDA 21 CFR Part 11", "Joint Commission"],
    specialRequirements: [
      "Medical Device Security",
      "Patient Data Protection",
      "Telemedicine Support",
      "Emergency Access Procedures",
      "Audit Trail Requirements",
    ],
    commonDevices: [
      "Medical Workstations",
      "Imaging Equipment",
      "Patient Monitors",
      "Infusion Pumps",
      "Mobile Carts",
      "Tablets for Nurses",
      "BYOD Smartphones",
    ],
    networkSegments: [
      "Clinical Network",
      "Administrative Network",
      "Medical Device Network",
      "Guest Network",
      "Research Network",
      "Emergency Network",
    ],
    securityPolicies: [
      "Device Authentication Required",
      "Encryption in Transit and at Rest",
      "Role-Based Access Control",
      "Time-Based Access Restrictions",
      "Device Compliance Validation",
      "Audit Logging",
    ],
    riskFactors: [
      "Patient Safety Impact",
      "Regulatory Compliance",
      "Data Breach Costs",
      "Medical Device Vulnerabilities",
      "Insider Threats",
    ],
    sampleSites: [
      {
        name: "Main Hospital Campus",
        type: "Hospital",
        users: 2500,
        devices: 8500,
        location: "Downtown Medical Center",
        priority: "Critical",
        budget: 850000,
        timeline: "18 months",
        specialRequirements: ["24/7 Operations", "Emergency Access", "Medical Device Integration"],
      },
      {
        name: "Outpatient Clinic Network",
        type: "Clinic",
        users: 450,
        devices: 1200,
        location: "Suburban Locations (5 sites)",
        priority: "High",
        budget: 180000,
        timeline: "12 months",
        specialRequirements: ["Telemedicine", "Mobile Device Support", "Patient Portal Access"],
      },
      {
        name: "Research Facility",
        type: "Research",
        users: 180,
        devices: 650,
        location: "University Campus",
        priority: "Medium",
        budget: 120000,
        timeline: "9 months",
        specialRequirements: ["Data Isolation", "Collaboration Tools", "High-Performance Computing"],
      },
    ],
  },
  financial: {
    id: "financial",
    name: "Financial Services",
    icon: "🏦",
    color: "#10B981",
    description: "Financial institutions with stringent regulatory requirements and high-security standards",
    compliance: ["PCI DSS", "SOX", "GDPR", "FFIEC", "Basel III", "GLBA"],
    specialRequirements: [
      "Trading Floor Security",
      "Fraud Detection Integration",
      "Regulatory Compliance Monitoring",
      "High-Frequency Trading Support",
      "Customer Data Protection",
    ],
    commonDevices: [
      "Trading Workstations",
      "ATM Networks",
      "Point of Sale Systems",
      "Mobile Banking Devices",
      "Compliance Monitoring Systems",
      "Executive Mobile Devices",
    ],
    networkSegments: [
      "Trading Network",
      "Corporate Network",
      "Customer-Facing Network",
      "Compliance Network",
      "ATM Network",
      "Guest Network",
    ],
    securityPolicies: [
      "Multi-Factor Authentication",
      "Certificate-Based Authentication",
      "Network Segmentation",
      "Data Loss Prevention",
      "Privileged Access Management",
      "Continuous Monitoring",
    ],
    riskFactors: [
      "Financial Loss",
      "Regulatory Penalties",
      "Reputation Damage",
      "Market Manipulation",
      "Insider Trading",
    ],
    sampleSites: [
      {
        name: "Corporate Headquarters",
        type: "Headquarters",
        users: 3200,
        devices: 12000,
        location: "Financial District",
        priority: "Critical",
        budget: 1200000,
        timeline: "24 months",
        specialRequirements: ["Trading Floor", "Executive Protection", "Disaster Recovery"],
      },
      {
        name: "Regional Branch Network",
        type: "Branch",
        users: 850,
        devices: 2800,
        location: "Multiple Cities (12 branches)",
        priority: "High",
        budget: 420000,
        timeline: "15 months",
        specialRequirements: ["Customer Access", "ATM Integration", "Vault Security"],
      },
      {
        name: "Data Center Facility",
        type: "Data Center",
        users: 120,
        devices: 1500,
        location: "Secure Location",
        priority: "Critical",
        budget: 380000,
        timeline: "12 months",
        specialRequirements: ["Physical Security", "Environmental Monitoring", "Backup Systems"],
      },
    ],
  },
  manufacturing: {
    id: "manufacturing",
    name: "Manufacturing",
    icon: "🏭",
    color: "#3B82F6",
    description: "Manufacturing facilities with operational technology integration and safety requirements",
    compliance: ["IEC 62443", "NIST 800-82", "ISO 27001", "OSHA", "EPA"],
    specialRequirements: [
      "OT/IT Convergence",
      "Industrial Control Systems",
      "Safety System Integration",
      "Production Line Monitoring",
      "Supply Chain Security",
    ],
    commonDevices: [
      "HMI Workstations",
      "PLC Controllers",
      "SCADA Systems",
      "Industrial Sensors",
      "Maintenance Tablets",
      "Quality Control Systems",
      "Inventory Scanners",
    ],
    networkSegments: [
      "Production Network",
      "Corporate Network",
      "Safety Systems Network",
      "Maintenance Network",
      "Quality Control Network",
      "Visitor Network",
    ],
    securityPolicies: [
      "OT Network Isolation",
      "Change Control Procedures",
      "Safety System Protection",
      "Vendor Access Control",
      "Asset Inventory Management",
      "Incident Response",
    ],
    riskFactors: [
      "Production Downtime",
      "Safety Incidents",
      "Quality Issues",
      "Intellectual Property Theft",
      "Supply Chain Disruption",
    ],
    sampleSites: [
      {
        name: "Primary Manufacturing Plant",
        type: "Manufacturing",
        users: 1800,
        devices: 15000,
        location: "Industrial Complex",
        priority: "Critical",
        budget: 950000,
        timeline: "20 months",
        specialRequirements: ["24/7 Production", "Safety Systems", "Environmental Monitoring"],
      },
      {
        name: "Assembly Facilities",
        type: "Assembly",
        users: 650,
        devices: 4200,
        location: "Multiple Locations (3 sites)",
        priority: "High",
        budget: 320000,
        timeline: "14 months",
        specialRequirements: ["Just-in-Time Production", "Quality Control", "Logistics Integration"],
      },
      {
        name: "R&D Center",
        type: "Research",
        users: 280,
        devices: 1100,
        location: "Technology Park",
        priority: "High",
        budget: 180000,
        timeline: "10 months",
        specialRequirements: ["IP Protection", "Collaboration Tools", "Prototype Testing"],
      },
    ],
  },
  technology: {
    id: "technology",
    name: "Technology",
    icon: "💻",
    color: "#8B5CF6",
    description: "Technology companies with cloud-first approaches and DevSecOps requirements",
    compliance: ["SOC 2", "GDPR", "ISO 27001", "FedRAMP", "CCPA"],
    specialRequirements: [
      "Cloud Security Integration",
      "DevSecOps Pipeline Security",
      "Intellectual Property Protection",
      "Remote Work Support",
      "API Security",
    ],
    commonDevices: [
      "Developer Workstations",
      "Cloud Instances",
      "Mobile Development Devices",
      "Testing Equipment",
      "IoT Prototypes",
      "Remote Work Laptops",
      "BYOD Devices",
    ],
    networkSegments: [
      "Development Network",
      "Production Network",
      "Testing Network",
      "Corporate Network",
      "Guest Network",
      "IoT Lab Network",
    ],
    securityPolicies: [
      "Zero Trust Architecture",
      "Continuous Integration Security",
      "Code Repository Protection",
      "API Gateway Security",
      "Container Security",
      "Cloud Workload Protection",
    ],
    riskFactors: [
      "Source Code Theft",
      "Data Breaches",
      "Service Disruption",
      "Competitive Intelligence",
      "Regulatory Compliance",
    ],
    sampleSites: [
      {
        name: "Corporate Campus",
        type: "Campus",
        users: 2200,
        devices: 8500,
        location: "Silicon Valley",
        priority: "Critical",
        budget: 750000,
        timeline: "16 months",
        specialRequirements: ["Open Collaboration", "BYOD Support", "Cloud Integration"],
      },
      {
        name: "Development Centers",
        type: "Development",
        users: 850,
        devices: 3200,
        location: "Multiple Cities (4 sites)",
        priority: "High",
        budget: 380000,
        timeline: "12 months",
        specialRequirements: ["High-Performance Computing", "Secure Development", "Remote Access"],
      },
      {
        name: "Customer Support Centers",
        type: "Support",
        users: 420,
        devices: 1200,
        location: "Global Locations (6 sites)",
        priority: "Medium",
        budget: 150000,
        timeline: "8 months",
        specialRequirements: ["24/7 Operations", "Customer Data Access", "Multi-language Support"],
      },
    ],
  },
  retail: {
    id: "retail",
    name: "Retail",
    icon: "🛍️",
    color: "#F59E0B",
    description: "Retail organizations with POS systems, customer data, and loss prevention requirements",
    compliance: ["PCI DSS", "CCPA", "GDPR", "SOX", "State Privacy Laws"],
    specialRequirements: [
      "POS System Security",
      "Customer Data Protection",
      "Loss Prevention Integration",
      "Inventory Management",
      "Omnichannel Support",
    ],
    commonDevices: [
      "Point of Sale Systems",
      "Inventory Scanners",
      "Security Cameras",
      "Mobile POS Devices",
      "Customer Kiosks",
      "Staff Tablets",
      "RFID Readers",
    ],
    networkSegments: [
      "POS Network",
      "Corporate Network",
      "Inventory Network",
      "Security Network",
      "Customer WiFi",
      "Staff Network",
    ],
    securityPolicies: [
      "PCI DSS Compliance",
      "Payment Data Protection",
      "Customer Privacy Protection",
      "Loss Prevention Monitoring",
      "Seasonal Access Control",
      "Vendor Management",
    ],
    riskFactors: [
      "Payment Card Fraud",
      "Customer Data Breach",
      "Inventory Theft",
      "Seasonal Traffic Spikes",
      "Regulatory Penalties",
    ],
    sampleSites: [
      {
        name: "Flagship Store",
        type: "Retail Store",
        users: 180,
        devices: 850,
        location: "Premium Shopping District",
        priority: "High",
        budget: 120000,
        timeline: "6 months",
        specialRequirements: ["High Customer Traffic", "Premium Experience", "Loss Prevention"],
      },
      {
        name: "Regional Store Network",
        type: "Store Network",
        users: 1200,
        devices: 4800,
        location: "Multiple Locations (24 stores)",
        priority: "High",
        budget: 480000,
        timeline: "18 months",
        specialRequirements: ["Standardized Deployment", "Remote Management", "Seasonal Scaling"],
      },
      {
        name: "Distribution Center",
        type: "Warehouse",
        users: 320,
        devices: 2100,
        location: "Logistics Hub",
        priority: "Medium",
        budget: 180000,
        timeline: "10 months",
        specialRequirements: ["Inventory Tracking", "Logistics Integration", "Automated Systems"],
      },
    ],
  },
  education: {
    id: "education",
    name: "Education",
    icon: "🎓",
    color: "#6366F1",
    description: "Educational institutions with student privacy requirements and BYOD challenges",
    compliance: ["FERPA", "CIPA", "FISMA", "COPPA", "State Education Laws"],
    specialRequirements: [
      "Student Privacy Protection",
      "Research Data Security",
      "BYOD Management",
      "Content Filtering",
      "Academic Freedom Balance",
    ],
    commonDevices: [
      "Student Laptops",
      "Classroom Tablets",
      "Interactive Whiteboards",
      "Research Workstations",
      "BYOD Smartphones",
      "Faculty Devices",
      "Campus IoT Sensors",
    ],
    networkSegments: [
      "Student Network",
      "Faculty Network",
      "Research Network",
      "Administrative Network",
      "Guest Network",
      "Campus Services Network",
    ],
    securityPolicies: [
      "Student Data Protection",
      "Content Filtering",
      "Time-Based Access Control",
      "Research Data Isolation",
      "BYOD Device Management",
      "Academic Integrity Monitoring",
    ],
    riskFactors: [
      "Student Privacy Violations",
      "Research Data Theft",
      "Inappropriate Content Access",
      "Cyberbullying",
      "Academic Dishonesty",
    ],
    sampleSites: [
      {
        name: "Main Campus",
        type: "University",
        users: 15000,
        devices: 45000,
        location: "University Town",
        priority: "Critical",
        budget: 1800000,
        timeline: "24 months",
        specialRequirements: ["24/7 Student Access", "Research Support", "Campus-wide Coverage"],
      },
      {
        name: "Satellite Campuses",
        type: "Branch Campus",
        users: 3200,
        devices: 8500,
        location: "Multiple Cities (3 campuses)",
        priority: "High",
        budget: 650000,
        timeline: "18 months",
        specialRequirements: ["Distance Learning", "Resource Sharing", "Unified Management"],
      },
      {
        name: "Research Facilities",
        type: "Research",
        users: 450,
        devices: 1800,
        location: "Science Park",
        priority: "High",
        budget: 280000,
        timeline: "12 months",
        specialRequirements: ["High-Security Labs", "Collaboration Tools", "Data Protection"],
      },
    ],
  },
  government: {
    id: "government",
    name: "Government",
    icon: "🏛️",
    color: "#6B7280",
    description: "Government agencies with strict security requirements and compliance mandates",
    compliance: ["FISMA", "NIST 800-53", "FedRAMP", "CJIS", "ITAR"],
    specialRequirements: [
      "Classified Information Protection",
      "Continuous Monitoring",
      "Insider Threat Detection",
      "Multi-Level Security",
      "Emergency Response Capability",
    ],
    commonDevices: [
      "Secure Workstations",
      "Mobile Command Units",
      "Surveillance Systems",
      "Communication Devices",
      "Biometric Scanners",
      "Emergency Response Equipment",
      "Field Tablets",
    ],
    networkSegments: [
      "Classified Network",
      "Unclassified Network",
      "Public Services Network",
      "Emergency Network",
      "Administrative Network",
      "Visitor Network",
    ],
    securityPolicies: [
      "Multi-Level Security",
      "Continuous Monitoring",
      "Insider Threat Detection",
      "Physical Security Integration",
      "Emergency Access Procedures",
      "Audit and Compliance",
    ],
    riskFactors: [
      "National Security Threats",
      "Classified Data Exposure",
      "Insider Threats",
      "Foreign Intelligence",
      "Public Safety Impact",
    ],
    sampleSites: [
      {
        name: "Federal Building Complex",
        type: "Government",
        users: 2800,
        devices: 8500,
        location: "Capital District",
        priority: "Critical",
        budget: 1500000,
        timeline: "30 months",
        specialRequirements: ["Security Clearance Levels", "Physical Security", "Continuity of Operations"],
      },
      {
        name: "Regional Offices",
        type: "Regional Office",
        users: 850,
        devices: 2400,
        location: "Multiple States (8 offices)",
        priority: "High",
        budget: 580000,
        timeline: "20 months",
        specialRequirements: ["Secure Communications", "Public Access", "Disaster Recovery"],
      },
      {
        name: "Emergency Operations Center",
        type: "Emergency",
        users: 120,
        devices: 650,
        location: "Secure Facility",
        priority: "Critical",
        budget: 420000,
        timeline: "15 months",
        specialRequirements: ["24/7 Operations", "Redundant Systems", "Multi-Agency Coordination"],
      },
    ],
  },
}

export function getIndustryScenario(industryId: string): IndustryScenario | null {
  return INDUSTRY_SCENARIOS[industryId] || null
}

export function getAllIndustryScenarios(): IndustryScenario[] {
  return Object.values(INDUSTRY_SCENARIOS)
}

export function generateIndustryDemoData(industryId: string, siteCount = 5): any[] {
  const scenario = getIndustryScenario(industryId)
  if (!scenario) return []

  const sites = []
  const sampleSites = scenario.sampleSites

  for (let i = 0; i < siteCount; i++) {
    const baseSite = sampleSites[i % sampleSites.length]
    const site = {
      id: `site-${industryId}-${i + 1}`,
      name: i < sampleSites.length ? baseSite.name : `${baseSite.type} ${i + 1}`,
      location: baseSite.location,
      industry: industryId,
      type: baseSite.type,
      status: ["Planning", "In Progress", "Complete", "On Hold"][Math.floor(Math.random() * 4)],
      priority: baseSite.priority,
      budget: baseSite.budget + (Math.random() - 0.5) * baseSite.budget * 0.2,
      timeline: baseSite.timeline,
      users: Math.floor(baseSite.users + (Math.random() - 0.5) * baseSite.users * 0.3),
      devices: Math.floor(baseSite.devices + (Math.random() - 0.5) * baseSite.devices * 0.3),
      completionPercent: Math.floor(Math.random() * 100),
      region: ["North America", "Europe", "Asia Pacific", "Latin America"][Math.floor(Math.random() * 4)],
      country: ["United States", "Canada", "United Kingdom", "Germany", "Japan", "Australia"][
        Math.floor(Math.random() * 6)
      ],
      compliance: scenario.compliance,
      specialRequirements: baseSite.specialRequirements,
      networkSegments: scenario.networkSegments,
      securityPolicies: scenario.securityPolicies,
      riskLevel: ["Low", "Medium", "High", "Critical"][Math.floor(Math.random() * 4)],
      lastUpdated: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString(),
      createdBy: `${scenario.name} Admin`,
      assignedTeam: ["Project Manager", "Network Engineer", "Security Analyst", "Compliance Officer"],
      infrastructure: {
        wiredVendor: ["cisco", "aruba", "juniper"][Math.floor(Math.random() * 3)],
        wirelessVendor: ["cisco", "aruba", "ruckus"][Math.floor(Math.random() * 3)],
        firewallVendor: ["palo_alto", "fortinet", "checkpoint"][Math.floor(Math.random() * 3)],
        switches: Math.floor(Math.random() * 50) + 10,
        accessPoints: Math.floor(Math.random() * 100) + 20,
        firewalls: Math.floor(Math.random() * 5) + 2,
      },
      connectivity: {
        internet: true,
        mpls: Math.random() > 0.5,
        vpn: true,
        sdwan: Math.random() > 0.3,
        satellite: Math.random() > 0.8,
      },
      identityProviders: ["azure_ad", "okta", "ping"][Math.floor(Math.random() * 3)],
      mdmProvider: ["intune", "jamf", "workspace_one"][Math.floor(Math.random() * 3)],
      authTypes: ["802.1x", "mac_auth", "web_auth"],
      deviceTypes: scenario.commonDevices,
      phases: [
        {
          name: "Planning & Design",
          status: "Complete",
          startDate: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
          endDate: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
          progress: 100,
        },
        {
          name: "Infrastructure Deployment",
          status: "In Progress",
          startDate: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
          endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
          progress: Math.floor(Math.random() * 80) + 20,
        },
        {
          name: "Policy Configuration",
          status: "Pending",
          startDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
          endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
          progress: 0,
        },
        {
          name: "Testing & Validation",
          status: "Pending",
          startDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
          endDate: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000).toISOString(),
          progress: 0,
        },
        {
          name: "Production Rollout",
          status: "Pending",
          startDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
          endDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
          progress: 0,
        },
      ],
    }

    sites.push(site)
  }

  return sites
}
