// lib/mock-data.ts

import type { Project, DashboardMetric, User } from "@/types"

export const mockUser: User = {
  name: "Alex Rivera",
  email: "alex.rivera@portnox.com",
  avatar: "/placeholder.svg?height=40&width=40",
  role: "Admin",
}

export const mockDashboardMetrics: DashboardMetric[] = [
  {
    title: "Active Projects",
    value: "128",
    change: "+5.2%",
    changeType: "increase",
    description: "from last month",
  },
  {
    title: "Deployment Health",
    value: "92%",
    change: "-1.8%",
    changeType: "decrease",
    description: "overall success rate",
  },
  {
    title: "Resources Utilized",
    value: "85%",
    change: "+3.1%",
    changeType: "increase",
    description: "across all projects",
  },
  {
    title: "Budget Variance",
    value: "-2.4%",
    change: "+0.5%",
    changeType: "increase",
    description: "average across portfolio",
  },
]

export const mockProjects: Project[] = [
  {
    id: "PROJ-001",
    name: "Global Financials HQ Rollout",
    type: "Production",
    phase: "Implementation",
    status: "On Track",
    health_score: { overall: 95, schedule: 98, budget: 92, resources: 95 },
    customer: "Global Bank Corp",
    project_manager: "Alice Johnson",
    start_date: "2024-03-01",
    end_date: "2025-06-30",
    completion_percentage: 65,
  },
  {
    id: "PROJ-002",
    name: "Healthcare IoT Security POC",
    type: "POC",
    phase: "Testing",
    status: "At Risk",
    health_score: { overall: 68, schedule: 60, budget: 75, resources: 70 },
    customer: "United Health Services",
    project_manager: "Bob Williams",
    start_date: "2024-06-15",
    end_date: "2024-09-15",
    completion_percentage: 80,
  },
  {
    id: "PROJ-003",
    name: "Retail Chain SD-WAN Integration",
    type: "Expansion",
    phase: "Design",
    status: "On Track",
    health_score: { overall: 98, schedule: 100, budget: 95, resources: 99 },
    customer: "FashionForward Retail",
    project_manager: "Charlie Brown",
    start_date: "2024-07-01",
    end_date: "2025-01-31",
    completion_percentage: 25,
  },
  {
    id: "PROJ-004",
    name: "Manufacturing OT Network Seg",
    type: "Production",
    phase: "Deployment",
    status: "Off Track",
    health_score: { overall: 45, schedule: 30, budget: 60, resources: 50 },
    customer: "Industrial Motors Inc.",
    project_manager: "Diana Prince",
    start_date: "2024-02-01",
    end_date: "2024-12-20",
    completion_percentage: 70,
  },
  {
    id: "PROJ-005",
    name: "University Campus Wireless Upgrade",
    type: "Migration",
    phase: "Optimization",
    status: "Completed",
    health_score: { overall: 100, schedule: 100, budget: 100, resources: 100 },
    customer: "State University",
    project_manager: "Eve Adams",
    start_date: "2023-08-01",
    end_date: "2024-05-30",
    completion_percentage: 100,
  },
  {
    id: "PROJ-006",
    name: "APAC Regional Office Pilot",
    type: "Pilot",
    phase: "Discovery",
    status: "Planning",
    health_score: { overall: 90, schedule: 90, budget: 90, resources: 90 },
    customer: "Tech Solutions Ltd.",
    project_manager: "Frank Miller",
    start_date: "2024-08-01",
    end_date: "2024-11-30",
    completion_percentage: 10,
  },
]
