import type {
  Site,
  User,
  Vendor,
  DeviceType,
  ChecklistItem,
  BaseVendor,
  UseCase,
  TestMatrixEntry,
  Requirement,
} from "./database"

export const mockUsers: User[] = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.j@example.com",
    role: "Senior Project Manager",
    user_type: "project_manager",
    created_at: "2025-01-10T10:00:00Z",
    updated_at: "2025-01-10T10:00:00Z",
  },
  {
    id: 2,
    name: "Bob Williams",
    email: "bob.w@example.com",
    role: "Project Manager",
    user_type: "project_manager",
    created_at: "2025-01-11T11:00:00Z",
    updated_at: "2025-01-11T11:00:00Z",
  },
  {
    id: 7,
    name: "Charlie Brown",
    email: "charlie.b@example.com",
    role: "Network Engineer",
    user_type: "technical_owner",
    created_at: "2025-01-12T12:00:00Z",
    updated_at: "2025-01-12T12:00:00Z",
  },
  {
    id: 8,
    name: "Diana Prince",
    email: "diana.p@example.com",
    role: "Security Engineer",
    user_type: "technical_owner",
    created_at: "2025-01-13T13:00:00Z",
    updated_at: "2025-01-13T13:00:00Z",
  },
]

export const mockWiredVendors: Vendor[] = [
  { id: 1, name: "Cisco", type: "wired", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 2, name: "Juniper", type: "wired", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 3, name: "Arista", type: "wired", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 4, name: "HPE/Aruba", type: "wired", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 5, name: "Extreme Networks", type: "wired", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 6, name: "Dell", type: "wired", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
]

export const mockWirelessVendors: Vendor[] = [
  { id: 14, name: "Cisco/Meraki", type: "wireless", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 15, name: "HPE/Aruba", type: "wireless", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 16, name: "Ubiquiti", type: "wireless", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 17, name: "Ruckus (CommScope)", type: "wireless", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 18, name: "Juniper Mist", type: "wireless", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 19, name: "Extreme Networks", type: "wireless", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
]

export const mockFirewallVendors: BaseVendor[] = [
  { id: 1, name: "Palo Alto Networks" },
  { id: 2, name: "Fortinet" },
  { id: 3, name: "Cisco" },
  { id: 4, name: "Check Point" },
  { id: 5, name: "Juniper" },
  { id: 6, name: "Sophos" },
]

export const mockVpnVendors: BaseVendor[] = [
  { id: 1, name: "Cisco AnyConnect" },
  { id: 2, name: "Palo Alto GlobalProtect" },
  { id: 3, name: "FortiClient" },
  { id: 4, name: "OpenVPN" },
  { id: 5, name: "Zscaler" },
  { id: 6, name: "NetMotion" },
]

export const mockEdrXdrVendors: BaseVendor[] = [
  { id: 1, name: "CrowdStrike Falcon" },
  { id: 2, name: "Microsoft Defender for Endpoint" },
  { id: 3, name: "SentinelOne" },
  { id: 4, name: "Palo Alto Cortex XDR" },
  { id: 5, name: "Trend Micro" },
  { id: 6, name: "Cybereason" },
]

export const mockSiemVendors: BaseVendor[] = [
  { id: 1, name: "Splunk" },
  { id: 2, name: "Microsoft Sentinel" },
  { id: 3, name: "IBM QRadar" },
  { id: 4, name: "LogRhythm" },
  { id: 5, name: "Exabeam" },
  { id: 6, name: "Securonix" },
]

export const mockDeviceTypes: DeviceType[] = [
  { id: 1, name: "Windows", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 2, name: "macOS", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 3, name: "iOS", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 4, name: "Android", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 5, name: "Linux", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 6, name: "Surveillance Camera", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 7, name: "IP Phone", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 8, name: "Printer", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 9, name: "Scanner", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 10, name: "HVAC Controller", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 11, name: "Badge Reader", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 12, name: "Industrial Sensor", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
]

export const mockChecklistItems: ChecklistItem[] = [
  { id: 1, name: "Microsoft Intune", category: "MDM/UEM", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 2, name: "VMware Workspace ONE", category: "MDM/UEM", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 3, name: "Jamf Pro", category: "MDM/UEM", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 4, name: "Kandji", category: "MDM/UEM", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 5, name: "MaaS360", category: "MDM/UEM", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 6, name: "ManageEngine", category: "MDM/UEM", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 7, name: "NinjaOne", category: "MDM/UEM", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 8, name: "Okta", category: "SSO/MFA", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 9, name: "Microsoft Entra ID", category: "SSO/MFA", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 10, name: "Ping Identity", category: "SSO/MFA", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  { id: 11, name: "Duo Security", category: "SSO/MFA", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
  {
    id: 12,
    name: "AD Broker Deployed",
    category: "Infrastructure",
    is_custom: false,
    created_at: "2025-01-01T00:00:00Z",
  },
  {
    id: 13,
    name: "Local RADIUS (Container)",
    category: "Infrastructure",
    is_custom: false,
    created_at: "2025-01-01T00:00:00Z",
  },
  {
    id: 14,
    name: "Local RADIUS (VM)",
    category: "Infrastructure",
    is_custom: false,
    created_at: "2025-01-01T00:00:00Z",
  },
  {
    id: 15,
    name: "TACACS+ Deployed",
    category: "Infrastructure",
    is_custom: false,
    created_at: "2025-01-01T00:00:00Z",
  },
  { id: 16, name: "ZTNA (SaaS)", category: "Infrastructure", is_custom: false, created_at: "2025-01-01T00:00:00Z" },
]

export const requirementsData: Requirement[] = [
  {
    id: "REQ-01",
    description: "Corporate devices must use certificate-based authentication (EAP-TLS).",
    justification: "Ensures only managed and trusted devices can connect.",
    metStatus: "Met",
  },
  {
    id: "REQ-02",
    description: "Guest network must be isolated from the corporate network.",
    justification: "Prevents unauthorized access to internal resources from guest devices.",
    metStatus: "Met",
  },
  {
    id: "REQ-03",
    description: "IoT devices must be placed in a segmented VLAN.",
    justification: "Limits the attack surface of potentially vulnerable IoT devices.",
    metStatus: "Not Met",
  },
  {
    id: "REQ-04",
    description: "Devices with high-risk vulnerabilities must be quarantined.",
    justification: "Prevents compromised devices from spreading threats.",
    metStatus: "Met",
  },
]

export const useCasesData: UseCase[] = [
  {
    id: "UC-01",
    title: "Wired 802.1X for Corporate Windows Devices",
    category: "Wired Access",
    description:
      "Ensure only corporate-managed Windows devices, authenticated via EAP-TLS with certificates from Intune, can access the wired network.",
    priority: "mandatory",
    status: "pending",
    completion_percentage: 0,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    requirement_ids: ["REQ-01"],
  },
  {
    id: "UC-02",
    title: "Wireless 802.1X for Corporate macOS Devices",
    category: "Wireless Access",
    description:
      "Ensure only corporate-managed macOS devices, authenticated via EAP-TLS with certificates from Jamf Pro, can access the corporate Wi-Fi.",
    priority: "mandatory",
    status: "pending",
    completion_percentage: 0,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    requirement_ids: ["REQ-01"],
  },
  {
    id: "UC-03",
    title: "Guest Wireless Access",
    category: "Wireless Access",
    description: "Provide time-limited, isolated internet access for guest users via a captive portal.",
    priority: "optional",
    status: "pending",
    completion_percentage: 0,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    requirement_ids: ["REQ-02"],
  },
  {
    id: "UC-04",
    title: "IoT Device Onboarding and Segmentation",
    category: "IoT/OT Security",
    description:
      "Onboard IoT devices (cameras, printers) using MAC authentication (MAB) and place them into a segmented, least-privilege network VLAN.",
    priority: "mandatory",
    status: "pending",
    completion_percentage: 0,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    requirement_ids: ["REQ-03"],
  },
  {
    id: "UC-05",
    title: "Risk-Based Access Control",
    category: "Security",
    description:
      "Dynamically change access for a device if a high-risk vulnerability is detected by the EDR/XDR integration (e.g., move to a quarantine VLAN).",
    priority: "nice-to-have",
    status: "pending",
    completion_percentage: 0,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    requirement_ids: ["REQ-04"],
  },
]

export const testMatrixData: TestMatrixEntry[] = [
  {
    id: "TM-01",
    platform: "MacOS",
    mode: "Agentless(SCEP+Jamf)",
    type: "Wired",
    configurationPortnoxCloud: "Completed",
    configurationCalixNAS: "Completed",
    configurationIntuneJamf: "Completed",
    dot1xConnectionTest: "Passed",
    manualBlockByAdmin: "Block only if re-connect[WIP]Portnox is investigating",
    aclTest: "Passed",
    riskAssessmentPolicyTest: "Passed",
    remediationPolicyTest: "Failed[WIP]Portnox is investigating",
    notes: "Aruba NAS use Local Radius/ Portnox Cloud Radius server",
    detectRisk: "All risk attributes",
    blockAction: "N/A",
    remark: "Not Start",
  },
  {
    id: "TM-02",
    platform: "Windows",
    mode: "Agentless (SCEP + Intune)",
    type: "Wired",
    configurationPortnoxCloud: "Completed",
    configurationCalixNAS: "Completed",
    configurationIntuneJamf: "Completed",
    dot1xConnectionTest: "Passed",
    manualBlockByAdmin: "Block only if re-connect[WIP]Portnox is investigating",
    aclTest: "Passed",
    riskAssessmentPolicyTest: "Passed",
    remediationPolicyTest: "Passed",
    notes:
      "1. China users' machine need to turn off proxy script during the deployment.2. Real time block requires CoA (Local redius Docker version only)",
    detectRisk: "Limited risk attributes",
    blockAction: "Block only if re-connect[WIP]Portnox is investigating",
    remark: "N/A",
  },
  {
    id: "TM-03",
    platform: "iOS(iPhone & iPad)",
    mode: "Agentless (SCEP + Intune + iOS)",
    type: "Wireless",
    configurationPortnoxCloud: "Completed",
    configurationCalixNAS: "Completed",
    configurationIntuneJamf: "Completed",
    dot1xConnectionTest: "Passed",
    manualBlockByAdmin: "Block only if re-connect[WIP]Portnox is investigating",
    aclTest: "Failed[WIP]Portnox is investigating",
    riskAssessmentPolicyTest: "Failed[WIP]Portnox is investigating",
    remediationPolicyTest: "In Progress",
    notes: "SCEP cert has been deployed, but not found SSID - NAC, will open intune case",
    detectRisk: "Limited risk attributes",
    blockAction: "Not Start",
    remark: "N/A",
  },
]

export const mockSites: Site[] = [
  {
    id: "HQ001",
    name: "Global Headquarters",
    region: "North America",
    country: "United States",
    priority: "High",
    phase: 1,
    users_count: 2500,
    project_manager_id: 1,
    radsec: "Native",
    planned_start: "2025-08-01",
    planned_end: "2025-08-15",
    status: "In Progress",
    completion_percent: 35,
    notes: "Executive network needs priority handling.",
    created_at: "2025-07-01T00:00:00Z",
    updated_at: "2025-07-15T00:00:00Z",
    technical_owners: [mockUsers[2]],
    vendors: [mockWiredVendors[0], mockWirelessVendors[0]],
    firewall_vendors: [mockFirewallVendors[0]],
    vpn_vendors: [mockVpnVendors[1]],
    edr_xdr_vendors: [mockEdrXdrVendors[1]],
    siem_vendors: [mockSiemVendors[1]],
    device_types: [mockDeviceTypes[0], mockDeviceTypes[1]],
    deployment_type: "hybrid",
    auth_methods: ["EAP-TLS", "SAML"],
    os_details: { windows: true, macos: true, ios: true, android: false, linux: false },
    checklist_items: [
      { ...mockChecklistItems[0], completed: true },
      { ...mockChecklistItems[8], completed: true },
    ],
    use_case_ids: ["UC-01", "UC-02"],
    test_matrix_ids: ["TM-01", "TM-02"],
  },
  {
    id: "EUR003",
    name: "European HQ",
    region: "EMEA",
    country: "Germany",
    priority: "Medium",
    phase: 2,
    users_count: 1200,
    project_manager_id: 2,
    radsec: "LRAD",
    planned_start: "2025-09-01",
    planned_end: "2025-09-15",
    status: "Planned",
    completion_percent: 0,
    notes: "GDPR compliance required.",
    created_at: "2025-07-02T00:00:00Z",
    updated_at: "2025-07-02T00:00:00Z",
    technical_owners: [mockUsers[3]],
    vendors: [mockWiredVendors[1], mockWirelessVendors[1]],
    firewall_vendors: [mockFirewallVendors[1]],
    vpn_vendors: [mockVpnVendors[2]],
    edr_xdr_vendors: [mockEdrXdrVendors[2]],
    siem_vendors: [mockSiemVendors[2]],
    device_types: [mockDeviceTypes[0], mockDeviceTypes[3]],
    deployment_type: "wired",
    auth_methods: ["EAP-TLS"],
    os_details: { windows: true, macos: false, ios: false, android: true, linux: false },
    checklist_items: [],
  },
]

export const mockCountries = [
  { name: "United States", code: "US" },
  { name: "Canada", code: "CA" },
  { name: "Mexico", code: "MX" },
  { name: "United Kingdom", code: "GB" },
  { name: "Germany", code: "DE" },
  { name: "France", code: "FR" },
  { name: "Japan", code: "JP" },
  { name: "China", code: "CN" },
  { name: "India", code: "IN" },
  { name: "Brazil", code: "BR" },
  { name: "Australia", code: "AU" },
]
