CREATE TABLE IF NOT EXISTS scoping_questionnaire (
    id SERIAL PRIMARY KEY,
    organization_name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    total_sites INTEGER,
    total_users INTEGER,
    network_vendors JSONB,
    switch_models JSONB,
    wireless_models JSONB,
    identity_providers JSONB,
    mdm_solutions JSONB,
    siem_solutions JSONB,
    mdr_solutions JSONB,
    xdr_solutions JSONB,
    edr_solutions JSONB,
    auth_methods JSONB,
    certificate_requirements JSONB,
    guest_access_requirements JSONB,
    byod_requirements JSONB,
    vlan_segmentation JSONB,
    access_policies JSONB,
    compliance_requirements JSONB,
    risk_tolerance VARCHAR(50),
    security_priorities JSONB,
    compliance_frameworks JSONB,
    target_deployment_date DATE,
    budget_range VARCHAR(100),
    project_timeline_months INTEGER,
    high_availability_required BOOLEAN,
    disaster_recovery_required BOOLEAN,
    multi_region_deployment BOOLEAN,
    status VARCHAR(50) DEFAULT 'submitted',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
