ALTER TABLE sites
ADD COLUMN IF NOT EXISTS user_count INTEGER,
ADD COLUMN IF NOT EXISTS device_types JSONB,
ADD COLUMN IF NOT EXISTS network_vendors JSONB,
ADD COLUMN IF NOT EXISTS auth_methods JSONB,
ADD COLUMN IF NOT EXISTS mdm_integration TEXT,
ADD COLUMN IF NOT EXISTS siem_integration TEXT,
ADD COLUMN IF NOT EXISTS sso_provider TEXT,
ADD COLUMN IF NOT EXISTS scoping_completed BOOLEAN DEFAULT FALSE;
